name: Publish
on: [workflow_dispatch]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        env:
          APIKEY: ${{ secrets.APIKEY }}
        run: .\publish.ps1
        shell: pwsh
